### ISSUE TITLE
Not working with Phoenix 1.2.1

### ISSUE THREAD

**Issue by cmalven** [nikkomiu/phoenix_inline_svg#4]
I followed your instructions exactly (including add the `use` statement to `web.ex` and when I try to compile my app I get the following error:

```
== Compilation error on file web/views/page_view.ex ==
** (CompileError) web/views/page_view.ex:2: unsupported option :otp_app given to import
    expanding macro: MyApp.Web.__using__/1
    web/views/page_view.ex:2: MyApp.PageView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/page_view.ex:2: MyApp.PageView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Any ideas?

**Comment by nikkomiu** [comment]
What version of `phoenix_inline_svg` are you using? I just noticed that the readme has the wrong version listed. Make sure to use version 1.0

**Comment by cmalven** [comment]
Thanks for the quick reply! That was definitely the to solution to that problem, so thank you.

Now I'm still getting an error, but it's a different one:

```
** (File.Error) could not list directory "/Users/me/Code/my-app/_build/dev/lib/my_app/priv/static/svg": no such file or directory
    (elixir) lib/file.ex:1174: File.ls!/1
    expanding macro: PhoenixInlineSvg.Helpers.__using__/1
    web/views/payload_view.ex:2: MyApp.PayloadView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/payload_view.ex:2: MyApp.PayloadView (module)
    expanding macro: MyApp.Web.__using__/1
    web/views/payload_view.ex:2: MyApp.PayloadView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/payload_view.ex:2: MyApp.PayloadView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I _do_ have a `/web/static/svg` directory, but I'm not entirely sure what it's looking for here. Is there anything I need to do here?

**Comment by nikkomiu** [comment]
Make sure you have the directory `svg` in `priv/static`. That is where the SVGs will live.

If you want to put them into a different directory there is a config option for that too.

**Comment by cmalven** [comment]
My mistake, I was placing the images in `/web/static/svg`. I'm pretty new to phoenix, so the difference between what goes in `/web/static/` and what goes in `/web/static/` is a still a little confusing to me.

Okay, one step closer. Now I'm getting an error when using `<%= svg_image("head-1") %>` (there is a file at `priv/static/svg/head-1.svg`):

```
== Compilation error on file web/views/user_view.ex ==
** (CompileError) web/templates/user/form.html.eex:50: undefined function svg_image/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Sorry to keep going back and forth with you like this, but I do appreciate the help.

**Comment by nikkomiu** [comment]
Try putting the svg file into a `generic` directory in the `/priv/static/svg`. So `/priv/static/svg/generic/head-1.svg`.

That was created due to a large set of SVGs and the need to group them into collections.

**Comment by cmalven** [comment]
Moved the file to `/priv/static/svg/generic/head-1.svg`. Still getting a similar issue:

```
== Compilation error on file web/views/user_view.ex ==
** (CompileError) web/templates/user/form.html.eex:50: undefined function svg_image/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by nikkomiu** [comment]
Did you add the following to the quoted section in the `def view` in your `web.ex`

```
use PhoenixInlineSvg.Helpers, otp_app: :my_app_name
```

Make sure to change **:my_app_name** to the name of your otp app.

**Comment by cmalven** [comment]
Yes. 

```
  def view do
    quote do
      use Phoenix.View, root: "web/templates"

      # Import convenience functions from controllers
      import Phoenix.Controller, only: [get_csrf_token: 0, get_flash: 2, view_module: 1]

      # Use all HTML functionality (forms, tags, etc)
      use Phoenix.HTML

      # Add SVG inline functionality
      use PhoenixInlineSvg.Helpers, otp_app: :git_hero

      import GitHero.Router.Helpers
      import GitHero.ErrorHelpers
      import GitHero.Gettext
    end
  end
```

**Comment by nikkomiu** [comment]
That was my fault on documentation. Try `<%= svg_image(@conn, "head-1") %>`

The `svg_image` function needs the connection.

**Comment by cmalven** [comment]
`no function clause matching in GitHero.UserView.svg_image/2` :-(

**Comment by nikkomiu** [comment]
Could you try to recompile your app?

**Comment by cmalven** [comment]
I ran `mix do clean, compile` and started the app up again. Same error. Is there a better way to recompile?

**Comment by nikkomiu** [comment]
That should do it. I will have to build a project to see what the issue could be.

**Comment by cmalven** [comment]
Thanks @nikkomiu. Appreciate your help.

**Comment by nikkomiu** [comment]
I looked at it and when calling you will need to use:

```elixir
PhoenixInlineSvg.Helpers.svg_image(@conn, "image_name")
```

You should be able to alias the `PhoenixInlineSvg.Helpers` module if needed.

**Comment by cmalven** [comment]
I did get this to work (thank you!) but it looks like it is wrapping the SVG it inlines with an `i` element and some identifying classes, which is working against me. Any way to turn this wrapper element off?

**Comment by nikkomiu** [comment]
There currently isn't a way to remove the wrapping. However, if you want to create a new issue I might be able to get to create a config option around making it possible to enable/disable the use of a wrapper next week.

**Comment by nikkomiu** [comment]
The wrapper has been removed to solve your issue.
